### ISSUE TITLE
As a user, I want to train custom hand gestures

### ISSUE THREAD

**Issue by MIDIBlocks** [MIDIBlocks/handsfree#107]
https://github.com/andypotato/fingerpose

## Objectives
- [x] Implement for TensorFlow Handpose
- [x] Implement for MediaPipe Hands
- [x] Document
- [x] Gestures boilerplate

## Documentation
- [x] `/ref/method/useGesture`
- [x] `/guide/gestures`
- [x] localStorage (`.lastCreatedGesture`)

## Trainer
- [x] Step 1: choose a model
- [x] Step 2: countdown for 3 seconds and record landmarks
- [x] Step 3: clean data
- [x] Step 4: generate description
- [x] Step 5: gesture properties

## Tasks
- [x] Model selector
- [x] Toggle buttons based on the selector
- [x] Clear Gesture
- [ ] Fix Twitter Embed warnings

**Comment by animaonline** [comment]
Hi! Is this supposed to track gestures across video frames? E.g. user swiping the hand? Also, are there any plans to use a NN to detect gestures?

**Comment by MIDIBlocks** [comment]
Hi! It only tracks static shapes like ✊, ☝, or ✌ right now but I do plan on supporting complex, multiframe gestures soon (hopefully by April or May). My next major focus is to make it super easy to "string" simpler shapes together to create complex gestures, which should be finished in a week or two...think of it like keyboard shortcuts but for gestures

I do plan on using NNs in addition to the simple description format I'm using now, but probably not until April/May when I implement multiframe gestures. The thing is that the description format is easy to edit/share (just copy/paste a string) whereas a NN model is a bit more involved (multiple binary files). It's not as great as a NN (ex: it's not subtle enough for the entire ASL alphabet) but if I went straight for NN I would not have made any progress for a few months 😅

**Comment by animaonline** [comment]
Awesome, thanks for your answer man :)
