### ISSUE TITLE
Hand Tracking Sandbox

### ISSUE THREAD

**Issue by MIDIBlocks** [MIDIBlocks/handsfree#63]
# First Pass
- [x] Add and document ability to load a new model by running `handsfree.start(opts)`
- [x] Add "Activate Finger Pointer" button that loads the model if not started
- [x] Do the same for the Face Pointer (in case this was activated before that one)
- [x] Show pointer on the screen

# Pinch Pointer
- [x] Cast a ray out from between the index finger and thumb
- [x] Pinch to click or drag

 # Documentation
- [x] Scroll focus
- [x] Hand Scroll
