### ISSUE TITLE
Handsfree.js 8.0 - MediaPipe Holistic

### ISSUE THREAD

**Issue by MIDIBlocks** [MIDIBlocks/handsfree#72]
## Focus
- Use Handsfree.js as a super quick way to get various models working
- Create lots of minimalist examples that can be forked (maybe on CodePen?)

## Notes
- https://google.github.io/mediapipe/solutions/holistic#javascript-solution-api
- https://google.github.io/mediapipe/getting_started/javascript.html
- https://google.github.io/mediapipe/solutions/holistic
- https://ai.googleblog.com/2020/12/mediapipe-holistic-simultaneous-face.html

## Tasks
- [x] Delete everything (handsfree.js and current docs) but keep styles etc
- [x] Everytime a new feature is added, document
- [x] `handsfree = new Handsfree({face: true, hand: true, pose: true})`
- [x] `handsfree.start()`
- [x] `handsfree.stop()` - Free up camera
- [x] `handsfree.use()`
- [x] `handsfree.update()`
- [x] Re-implement old plugins, but have them disabled by default
- [x] Toggle plugins by tag

## Touchup
- [x] Embed debugger in a draggable window component
